{
 "title": "External-DNS",
 "description": "External-DNS",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "degree" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"tools\",pod_name=~\"external-dns-deployment-tools.*\"}[3m]))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"tools\",pod_name=~\"external-dns-deployment-tools.*\"}) / 1024^3"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg(kube_pod_status_phase{namespace=~\"tools\",pod=~\"external-dns-deployment-tools.*\"}) by(namespace, pod, phase)) by(phase)",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Available Replicas",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(kube_deployment_status_replicas_available{deployment=\"external-dns-deployment-tools\",namespace=\"tools\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Desired Replicas",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(kube_deployment_spec_replicas{deployment=\"external-dns-deployment-tools\",namespace=\"tools\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Pod",
   "type": "graph",
   "description": "external-DNS pod",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_info{namespace=~\"tools\",pod=~\"external-dns-deployment-tools.*\"}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"tools\",pod_name=~\"external-dns-deployment-tools.*\"}[3m])) + sum(rate(container_network_receive_bytes_total{namespace=\"tools\",pod_name=~\"external-dns-deployment-tools.*\"}[3m]))"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(kube_deployment_status_replicas{deployment=\"external-dns-deployment-tools\",namespace=\"tools\"}) without (instance, pod)",
     "legendFormat": "current replicas"
    },
    {
     "expr": "min(kube_deployment_status_replicas_available{deployment=\"external-dns-deployment-tools\",namespace=\"tools\"}) without (instance, pod)",
     "legendFormat": "available"
    },
    {
     "expr": "max(kube_deployment_status_replicas_unavailable{deployment=\"external-dns-deployment-tools\",namespace=\"tools\"}) without (instance, pod)",
     "legendFormat": "unavailable"
    },
    {
     "expr": "min(kube_deployment_status_replicas_updated{deployment=\"external-dns-deployment-tools\",namespace=\"tools\"}) without (instance, pod)",
     "legendFormat": "updated"
    },
    {
     "expr": "max(kube_deployment_spec_replicas{deployment=\"external-dns-deployment-tools\",namespace=\"tools\"}) without (instance, pod)",
     "legendFormat": "desired"
    }
   ]
  }
 ]
}